// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA4oxC5uu_WjB0lHpcymRFQyxRUmViObUE',
    appId: '1:64764094905:web:2ba540ed046a683e57ee68',
    messagingSenderId: '64764094905',
    projectId: 'finsight-5f0b3',
    authDomain: 'finsight-5f0b3.firebaseapp.com',
    storageBucket: 'finsight-5f0b3.firebasestorage.app',
    measurementId: 'G-ZM6ZTML6BX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDnjpv2-2mntJ2_8vBJ9m0eBPoWc_tQg-c',
    appId: '1:64764094905:android:16500664228baf5157ee68',
    messagingSenderId: '64764094905',
    projectId: 'finsight-5f0b3',
    storageBucket: 'finsight-5f0b3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAKLQ_El_n6RxHLG9gEqgQNdSBI6sXdhLo',
    appId: '1:64764094905:ios:b2ac0f3537cfe3e157ee68',
    messagingSenderId: '64764094905',
    projectId: 'finsight-5f0b3',
    storageBucket: 'finsight-5f0b3.firebasestorage.app',
    iosBundleId: 'com.example.finsightV2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAKLQ_El_n6RxHLG9gEqgQNdSBI6sXdhLo',
    appId: '1:64764094905:ios:b2ac0f3537cfe3e157ee68',
    messagingSenderId: '64764094905',
    projectId: 'finsight-5f0b3',
    storageBucket: 'finsight-5f0b3.firebasestorage.app',
    iosBundleId: 'com.example.finsightV2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA4oxC5uu_WjB0lHpcymRFQyxRUmViObUE',
    appId: '1:64764094905:web:4c29c0feee31579857ee68',
    messagingSenderId: '64764094905',
    projectId: 'finsight-5f0b3',
    authDomain: 'finsight-5f0b3.firebaseapp.com',
    storageBucket: 'finsight-5f0b3.firebasestorage.app',
    measurementId: 'G-RY3RSGJZT2',
  );

}